actions/urls.py
from django.conf.urls import patterns, url
from actions import views

urlpatterns = patterns('actions.views',
        url(r'^vote/(?P<pk>\d+)$', 'Vote', name = 'vote'),
        url(r'^actions$', 'ViewAllActions', name = 'actions'),
        url(r'^details/(?P<pk>\d+)$', 'DetailsOfAction', 'details'),
               )

historicalarchives/urls.py
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'historicalarchives.views.Index', name = 'index'),
    url(r'^actions/', include('actions.urls', namespace="actions")),
    url(r'^materials/', include('materials.urls', namespace="materials")),
    url(r'^profiles/', include('profiles.urls', namespace="profiles")),
    url(r'^timeline/', include('timeline.urls', namespace="timeline")),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATICFILES_DIRS[0], 'show_indexes':True}),
    )

materials/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('materials.views',
        url(r'^search$', 'SearchForMaterial', name = 'search'),
        url(r'^details/(?P<pk>\d+)$', 'DetailsOfMaterials', name = 'details'),
        url(r'^add$', 'AddMaterial', name = 'add'),
        url(r'^viewnew$', 'ViewNewMaterials', name = 'viewnew'),
        url(r'^request_add$', 'RequestMaterial', name = 'request_add'),
        url(r'^requests$', 'ViewAllRequests', name = 'requests'),
        url(r'^request_details/(?P<pk>\d+)$', 'DetailsOfRequest', name = 'reqeust_detail'),
        url(r'^collection_build/(?P<pk>\d+)$', 'BuildCollection', name='collection_build'),
        url(r'^collection_details$', 'DetailsOfCollection', name='collection_details'),
        url(r'^collections$', 'ViewAllCollections', name='collections'),
        )

historicalarchives/models.py
# -*- coding: utf-8 -*-
from django.db import models
import datetime
from django.contrib.auth.models import User
#from tagging.fields import TagField
from django.utils import timezone
import datetime

class Material(models.Model):
    '''klasa dla materialow'''
    owner = models.ForeignKey(User) #wlascicielem jest uzytkownik,
    uploader = models.IPAddressField(null = True) #jesli material jest dodawany anonimowo, zapisujemy IP jako tworce
    title = models.CharField(max_length = 150, unique = True,)
    date = models.DateTimeField(blank = True) # DateTimeField jest tymczasowe, poniewaz nie zawsze mozna podac pelna date, czasami tylko rok, albo nawet dekade, dlatego trzeba bedzie to jakos zastapic
    #place = models.ForeignKey(Location)
    date_of_creation =  models.DateField(default=datetime.date.today()) #data powstania materialu czyli 'teraz' wypelniana automatycznie
    #type_of_media = #rodzaj medium: audio, video, plik graficzny,
    description = models.TextField()#opis materialu podany przez uzytkownika
    #tags = models.TagField()

    def add_to_collection(self, collection, user):
        if  collection.owner != public and collection.owner != User:
            print "Tylko wlasciciel kolekcji moze dodawac do niej nowe materiały."
        elif collection.owner == public or collection.owner == User:
            self.member_of_collections.append(collection)
            collection.materials_belonging.append(self)

class Collection(models.Model):
    '''klasa dla kolekcji'''
    #OWNER_CHOICES = ( #uzytkownik wybiera czy chce tworzyc kolekcje wlasna, czy publiczna
    #    (models.ForeignKey(User), 'Ja'),
    #    ('', 'Kolekcja publiczna'),
    #)
    #owner =  models.ChoiceField(blank = True, choices = OWNER_CHOICES, default = User) #wlascicielem jest uzytkownik, albo jest to kolekcja publiczna, wtedy blank - puste pole, ale by default owner == this_user
    founder = models.ForeignKey(User) # tworca kolekcji musi byc uzytkownikiem, ale nie musi byc tozsamy z wlascicielem
    title = models.CharField(max_length = 150, unique=True)
    date_of_creation =  models.DateField(default=datetime.date.today()) #data powstania materialu czyli 'teraz' wypelniana automatycznie
    materials_belonging = models.ManyToManyField(Material) # materialy ktore naleza do kolekcji
    def make_public(self):
        '''zamienia kolekcje z prywatnej w publiczną'''
        self.owner = ''

class Request_for_materials(models.Model):
    '''Model dla prosby o udostepnienie materialow'''
    issuer = models.ForeignKey(User) #osoba ktora publikuje prosbe
    title = models.CharField(max_length = 150, unique = True)
    date_of_creation =  models.DateField(default=datetime.date.today()) #data powstania materialu czyli 'teraz' wypelniana automatycznie
    description = models.TextField()#opis prosby o materiały podany przez uzytkownika

materials/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
#from tagging.fields import TagField
from django.utils import timezone
import datetime

class Material(models.Model):
    '''klasa dla materialow'''
    owner = models.ForeignKey(User) #wlascicielem jest uzytkownik,
    uploader = models.IPAddressField(null = True) #jesli material jest dodawany anonimowo, zapisujemy IP jako tworce
    title = models.CharField(max_length = 150, unique = True,)
    date = models.DateField(blank = True) # DateTimeField jest tymczasowe, poniewaz nie zawsze mozna podac pelna date, czasami tylko rok, albo nawet dekade, dlatego trzeba bedzie to jakos zastapic
    #place = models.ForeignKey(Location)
    date_of_creation =  models.DateTimeField(default=datetime.datetime.now()) #data powstania materialu czyli 'teraz' wypelniana automatycznie
    #type_of_media = #rodzaj medium: audio, video, plik graficzny,
    description = models.TextField()#opis materialu podany przez uzytkownika
    #tags = models.TagField()
    path = models.FilePathField()

    def add_to_collection(self, collection, user):
        if  collection.owner != public and collection.owner != User:
            print "Tylko wlasciciel kolekcji moze dodawac do niej nowe materiały."
        elif collection.owner == public or collection.owner == User:
            self.member_of_collections.append(collection)
            collection.materials_belonging.append(self)
    
class Collection(models.Model):
    '''klasa dla kolekcji'''
    #OWNER_CHOICES = ( #uzytkownik wybiera czy chce tworzyc kolekcje wlasna, czy publiczna
    #    (models.ForeignKey(User), 'Ja'),
    #    ('', 'Kolekcja publiczna'),
    #)
    #owner =  models.ChoiceField(blank = True, choices = OWNER_CHOICES, default = User) #wlascicielem jest uzytkownik, albo jest to kolekcja publiczna, wtedy blank - puste pole, ale by default owner == this_user
    founder = models.ForeignKey(User) # tworca kolekcji musi byc uzytkownikiem, ale nie musi byc tozsamy z wlascicielem
    description = models.TextField()#opis podany przez uzytkownika
    title = models.CharField(max_length = 150, unique=True)
    date_of_creation =  models.DateTimeField(default=datetime.datetime.now()) #data powstania materialu czyli 'teraz' wypelniana automatycznie
    materials_belonging = models.ManyToManyField(Material) # materialy ktore naleza do kolekcji
    def make_public(self):
        '''zamienia kolekcje z prywatnej w publiczną'''
        self.owner = ''
        
class Request_for_materials(models.Model):
    '''Model dla prosby o udostepnienie materialow'''
    issuer = models.ForeignKey(User) #osoba ktora publikuje prosbe
    title = models.CharField(max_length = 150, unique = True)
    date_of_creation =  models.DateTimeField(default=datetime.datetime.now()) #data powstania materialu czyli 'teraz' wypelniana automatycznie
    description = models.TextField()#opis prosby o materiały podany przez uzytkownika
    materials_in_response = models.ManyToManyField(Material)# materialy powstale w odpowiedzi na request
    

historicalarchives/forms.py
from django import forms
import datetime

class UploadMaterial(forms.Form)
    title  = forms.CharField(max_length = 100, help_text = 'Tytul')
    description = forms.TextField(help_text = 'Opis')
    date = forms.DateField(initial=datetime.date.today)
    #do zastnowienia place = 
    file = forms.FileField()

historicalarchives/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response

def Index(request):
    return render_to_response("historicalarchives/index.html", context_instance=RequestContext(request))

materials/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response
from materials.models import Material, Request_for_materials, Collection

def SearchForMaterial(request):
    return render_to_response('materials/materials_search.html', context_instance=RequestContext(request))

def DetailsOfMaterials(request, pk):
    material = Material.objects.get(pk = pk)
    return render_to_response("materials/material_details.html", {
        'material': material}, context_instance=RequestContext(request))

def AddMaterial(request):
    return render_to_response("materials/material_add.html", context_instance=RequestContext(request))

def ViewNewMaterials(request):
    materials = Material.objects.all().order_by('date_of_creation')[:10]
    return render_to_response("materials/view_new_materials.html", {
        "materials": materials}, context_instance=RequestContext(request))

def RequestMaterial(request):
    return render_to_response("materials/request_issue_new.html", context_instance=RequestContext(request))

def ViewAllRequests(request):
    requests = Request_for_materials.objects.all()
    return render_to_response("materials/requests.html", {
        'requests_list':requests}, context_instance=RequestContext(request))

def DetailsOfRequest(request, pk):
    request_for_materials = Request_for_materials.objects.get(pk = pk)
    return render_to_response("materials/request_details.html", {
        'request': request_for_materials}, context_instance=RequestContext(request))

def BuildCollection(request):
    return render_to_response("materials/collection_build.html", context_instance=RequestContext(request))

def DetailsOfCollection(request, pk):
    collection =Collection.objects.get(pk = pk)
    return render_to_response("materials/collection_details.html", {
        "collection": collection}, context_instance=RequestContext(request))

def ViewAllCollections(request):
    collections = Collection.objects.all()
    return render_to_response("materials/collections.html", {
        "collections": collections}, context_instance=RequestContext(request))

historicalarchives/templates/materials/collections.html
{% extends "base.html" %}

{% block title %}Obejrzyj kolekcje{% endblock %}
{% block content %}
<h1>Obejrzyj kolekcje </h1>
<p>Oto tytu&#322y kolekcji :</p>
<ul>
{% for collection in collections_list %}
<li>{{ collection }}</li>
{% endfor %}
</ul>
{% endblock %}

historicalarchives/templates/materials/material_add.html
{% extends "base.html" %}

{% block title %}Dodaj materia&#322{% endblock %}
{% block content %}
<h1>Dodaj nowy material</h1>
<p>Wype&#322nij poni&#380szy formularz </p>

<form method="post" action="">

<p>{% if form.title.errors %}
<span class="error">
{{ form.title.errors|join:", " }}
</span>
{% endif %}</p>

<p><label for="id_title">Tytu&#322:</label>
{{ form.title }}</p>

<p>{% if form.date.errors %}
<span class="error">
{{ form.date.errors|join:", " }}
</span>
{% endif %}</p>

<p><label for="id_date">Data:</label>
{{ form.date }}</p>

<p>{% if form.description.errors %}
<span class="error">
{{ form.description.errors|join:", " }}
</span>
{% endif %}</p>

<p><label for="id_description">Opis:</label></p>
<p>{{ form.description }}</p>

<p>{% if form.place.errors %}
<span class="error">
{{ form.place.errors|join:", " }}
</span>
{% endif %}</p>

<p><label for="id_code">Miejsce</label></p>
<p>{{ form.place }}</p>

<p>{% if form.tags.errors %}
<span class="error">
{{ form.tags.errors|join:", " }}
</span>
{% endif %}</p>


<p><label for="id_tags">Tagi:</label>
{{ form.tags }}</p>
<p><input type="submit" value="Nadus tutaj!"></p>

</form>
{% endblock %}

historicalarchives/templates/materials/material_details.html
{% extends "base.html" %}

{% block title %}Ogl&#261dnij materia&#322{% endblock %}
{% block content %}
<h1>Ogl&#261dnij materia&#322</h1>
<h2>Tytu&#322: {{ material.title }}</h2>

<p>Data: {{ material.date }}</p>

<p>Miejsce: {{ material.place }}</p>

<p>Opis: {{ material.description }}</p>

<p>Tw&#243rca: {{ material.owner }}</p>

<p>Data dodania: {{ material.date_of_creation }}</p>

<p>Tagi: {{ material.tagi }}</p>

<p>Ten material jest elementem nast&#281puj&#261cych kolekcji:
{{ material.member_of_collections }}</p>

{% endblock %}

historicalarchives/templates/materials/materials_search.html
{% extends "base.html" %}

{% block title %}Multiarchiwum - szukaj materia&#322u{% endblock %}
{% block content %}
<div>
<p>Przeszukaj materia&#322y</p>
 
 
 <form class="searchform">
	<input class="searchfield" type="text" value="Wpisz s&#322owo" onFocus="if (this.value == 'Search...') {this.value = '';}" onBlur="if (this.value == '') {this.value = 'Search...';}" />
<input class="searchbutton" type="button" value="Szukaj" />
</form></div>

{% endblock %} 

historicalarchives/templates/materials/request_details.html
{% extends "base.html" %}{% block title %}{% endblock %}{% block content %}{% endblock %}

historicalarchives/templates/materials/requests.html
{% extends "base.html" %}

{% block title %}Obejrzyj prosby o udost&#281pnienie materia&#322&#243w{% endblock %}
{% block content %}
<h1>Obejrzyj pro&#347by o udost&#281pnienie materia&#322&#243w </h1>
<p>Oto tytu&#322y pr&#243&#347b :</p>
<ul>
{% for request in requests_list %}
<li>{{ request }}</li>
{% endfor %}
</ul>

{% endblock %}

historicalarchives/templates/materials/view_new_materials.html
{% extends "base.html" %}

{% block title %}Ogl&#261dnij materia&#322y{% endblock %}
{% block content %}
<h1>Ogl&#261dnij nowe materia&#322y</h1>
{% for material in materials %}
<h2>Tytu&#322: {{ material.title }}</h2>

<p>Opis: {{ material.description|truncatewords:10}}</p>

<p>Tw&#243rca: {{ material.owner }}</p>

<p>Data dodania: {{ material.date_of_creation }}</p>
{% comment %}
<p>Tagi: {{ material.tagi }}</p>
{% endcomment%}
<p>Ten material jest elementem nast&#281puj&#261cych kolekcji:
{{ material.member_of_collections }}</p>
{% endfor %}
{% endblock %}